config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "tasks#index"
  
  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"
  get "details.:id", to: "tasks#details", as: :task
  get "/tasks/details.:id/edit", to: "tasks#edit", as: :edit_task
  patch "/details.:id", to: "tasks#update"
  delete "/tasks/:id", to: "tasks#destroy", as: :destroy 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def details 
    @task = Task.find(params[:id])
  end 

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to root_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
  
  private

  def task_params
    params.require(:task).permit(:title, :details)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css', integrity: 'correct-integrity-value', crossorigin: 'anonymous' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css', integrity: 'sha256-i1XaF66mF0Y3xVWjC8g+oJd07bcL/q6KRr+g7DnIAnk=', crossorigin: 'anonymous' %>
  </head>

  <body>
    <h1>my app</h1>
    <%= yield %>
  </body>
</html>

app/views/tasks/details.html.erb
<h1> <%= @task.title%></h1>
<h3> <%= @task.details%> </h3>
<h5><% if @task.completed == true %>
<%="This task is completed" %>
<% else %>
<%="This task is not completed" %>
<% end %>
</h5>

<%= link_to "Edit this task", edit_task_path  %>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<%end%>

app/views/tasks/index.html.erb
<head>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css', integrity: 'sha256-i1XaF66mF0Y3xVWjC8g+oJd07bcL/q6KRr+g7DnIAnk=', crossorigin: 'anonymous' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha256-i1XaF66mF0Y3xVWjC8g+oJd07bcL/q6KRr+g7DnIAnk=" crossorigin="anonymous">
</head>

<body>
  
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <li><%= link_to task.title, task_path(task.id) %></li>
      <%= link_to destroy_path(task),
                  data: { turbo_method: :delete,turbo_confirm: "Are you sure?" },
                  class: "delete-link" do %>
        <i class="fa fa-trash" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</ul>


<%= link_to "Add a new task", new_task_path  %>
</body>

app/views/tasks/new.html.erb
<h1>Details</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<%end%>